config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
	def self.search(search)
  	where("title LIKE ?", "%#{search}%") 
  	where("text LIKE ?", "%#{search}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only:[:show,:edit,:update,:destroy]

	def new
		@article = Article.new
	end

	def index
		@articles = Article.all
		if params[:search]
			@articles = Article.search(params[:search]).order("created_at DESC")
		else
			@articles = Article.all.order('created_at DESC')
		end
	end

	def show
	end
	
	def create
		@article = Article.new(article_params)
		if @article.save
    	redirect_to @article
  	else
    	render 'new'
  	end
	end
	
	def destroy
		@article.destroy
		redirect_to @article
	end
	
	def edit
	end
	
	def update
		if @article.update(article_params)
    	redirect_to @article
  	else
    	render 'edit'
  	end
	end
	
	private
		def article_params
			params.require(:article).permit(:title,:text)
		end
		
		def set_article
			@article = Article.find(params[:id])
		end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/image_post_helper.rb
module ImagePostHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
		<%= f.label :title, :class => 'new' %><br />
		<%= f.text_field :title, :class => 'new', :id => 'title'%><br />
		<%= f.label :text, :class => 'new' %><br />
		<%= f.text_area :text, :class => 'new', :id => 'text' %><br />
		<%= f.submit :class => 'new', :id => 'submit' %>
		<% if @article.errors.any? %>
			<div class="new" id="explanation">
				<h2 class="new" id="error_message"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved.</h2>
				<ul class="new" id="error_message">
					<% @article.errors.full_messages.each do |msg| %>
         		<li class="new" id="error_message"><%= msg %></li>
       		<% end %>
				</ul>
			</div>
		<% end %>
<% end %>

app/views/articles/edit.html.erb
<header>
	ParaSite - My Personal Website
</header>

<div class="new" id="form_container">
	<h1 class="new" id="form_title">Edit Article</h1>
	<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<header>
	ParaSite - My Personal Website
</header>

<div class="index" id="sidebar">
	<%= link_to 'Create a blog', new_article_path, :class => 'index', :id => 'sidebar_anchor' %>
</div>

<%= form_tag(articles_path, :method => "get", id: "search-form", :class => 'index_search') do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search Blogs", :class => 'index_search' %>
	<%= submit_tag "Search", :class => 'index_search', :id => 'submit_search' %>
<% end %>

<% if @articles.present? %>
  <%= render @articles %>
<% else %>
  <p class="index_search" id="bad_search">There are no blogs containing the term(s) <%= params[:search] %>.</p>
  <%= link_to 'Back', articles_path, :class => "index_search", :id => "back_portal" %>
<% end %>

<div id="clear_float"></div>
<% @articles.each do |article| %>
	<div class="index" id="article_box">
		<h1 class="index" id="header"><%= article.title %></h1>
		<p class="index" id="paragraph"><%= article.text %></p>
		<span class="index" id="time_posted">Created at: <%= article.created_at %></span>
		<% if article.created_at != article.updated_at%>
			<span class="index" id="time_posted">Updated at: <%= article.updated_at %></span>
		<% end %>
		<%= link_to 'View', article_path(article), :class => 'index', :id => 'view_anchor'%>
		<%= link_to 'Edit', edit_article_path(article), :class => 'index', :id => 'view_anchor'%>
		<%= link_to 'Delete', article_path(article), method: :delete, data:{confirm: 'Are you sure?'}, :class => 'index', :id => 'view_anchor' %>
		<div id="clear_float"></div>
	</div>
<% end %>

app/views/articles/new.html.erb
<header>
	ParaSite - My Personal Website
</header>


<div class="new" id="form_container">
	<h1 class="new" id="form_title">New Article</h1>
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<header>
	ParaSite - My Personal Website
</header>


<div class="show" id="article_container">
	<h1 class="show" id="title"><%= @article.title %></h1>
	<hr />
	<p class="show" id="text"><%= @article.text %></p>
	<span class="show" id="footnote">Created at: <%= @article.created_at %></span>
	<% if @article.created_at != @article.updated_at%>
		<span class="show" id="footnote">Updated at: <%= @article.updated_at %></span>
	<% end %>
	<%= link_to 'Back', articles_path, :class => "show", :id => "back_portal" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParaSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<header>
	ParaSite - My Personal Website
</header>
<div class="index" id="welcome_container">
	<h1 class="index">Welcome to ParaSite!</h1>
	<p class="index">This website was created for the express purpose of training in programming in Ruby on Rails,
	 specifically so that I can fulfill my duties as an intern and contribute to the project MIST, 
	 the data migration system project I was assigned to. Please do not judge the coding of this site, 
	 for I am taking a crash course to this programming language. After all, I have begun learning it a 
	 few days ago.</p>
	<%= link_to 'My Blog', {controller: 'articles'}, :class => 'index', :id => 'blog_portal' %>
</div>